// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package tekton

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "tekton", asset.ModuleFieldsPri, AssetTekton); err != nil {
		panic(err)
	}
}

// AssetTekton returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/tekton.
func AssetTekton() string {
	return "eJy8lsFy2yAQhu9+in9ySjqJHkCHPkKnk8k9wbCyqRCo7DKu3r6DLSmy62jUVC4XAwvst/96135CTV0JoVqC3wBixVGJu9PG3QaI5EgxldiSqA1giHW0rdjgS3zdAMDL8TCaYJKjDVBZcobLo+0JXjU08ZCHdC2V2MWQ2n7nyqt5vJ2uvUEHL8p6BosSy2I1Q/ZKcKBIiKQMqhiaAeW7bclZT3y8GINzFPtHp3BTwHa48ppd8Gi/RjtDPNHjHaIhiZn4/kVx/Zw8P47GvCqK4mHywKXiw7gkP5NXcR2TL3RIXs5ODPwu+N2FYSaEYxhBlMOADPpFOgkZbLs+wlmSmLy3frcq0bfUbCkiVO9UOsVIXlyH3uFVqCG5t5FomsulMk2JbivVGd3Hci2ZXOR4jSIZE9nXyEp1kFdXlaypO4Ro/jLNe8uwhrzYylLuPDSAH/0Wsyy5nyT+PzQnX7jnpDUxP6JS1pF5mCfMn2tVxAdwOZsql4UESD7znPw8VF5xq/SN8zi6wWGff0umalqGodaFjsw8q0lRZacFky62SdckxZer3GH7g/RlkZ82Xz+teY87UGBvWcIuqgYnFob1YNLBG14eB6dm6ZeiCrFRUo4E/8b/CE5Nbl3Dxuf4V230fyD6scFG+pmIJ38ZFk1+BwAA//9Wvpcy"
}
