// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package tekton

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "tekton", asset.ModuleFieldsPri, AssetTekton); err != nil {
		panic(err)
	}
}

// AssetTekton returns asset data.
// This is the base64 encoded gzipped contents of ../metricbeat/module/tekton.
func AssetTekton() string {
	return "eJy01MFy2jAQBuA7T/FPjp3ED+BDH6HTyeTeCGkB1fLK1a6G+u07wmCM43pSmugC1lqrj1+MntBQX0Op0cgbQL0GqvEwTDxsgESBjFCNLanZAI7EJt+pj1zj6wYAXk4vo40uB9oAO0/BSX2qPYFNS5MdytC+oxr7FHN3nlnoWsbrsOwVNrIazwJRo17UW4EejOJIiZDIOOxSbC+U776j4JnktDDFECidm05xN0AjTcosY2GJuUKdBPFipHnOLGhJk7fTlvM0L2OuupFFNeGmcqGFyPtZYUV3EpZeE6BhsyeHbX+2LwJSZvZvdrqX8C23W0qIuyuDfpPN6nkPm1Mi1tAvJzGcUeVyMqV9JWSrbbYNafVlkRe3P8nqrDRM/rg7w4GNiwIHLxr3ybQYLALPELKRnbz/d0hu35vwLqbWaD0K/s//CMltOY/LxH1+GzPPk/6oiB/B478m0a9MolfZKrE8LaIa6o8xuX90HbzAO2L1O0/lCqLRWnaqVi3l86MC+gukXDBGyUEjtLzznHkdVZ6kM/aTUxq3wfFQruxpcl7gqAuxJ1e9PdXrlz8BAAD///8D1MM="
}
